# Copyright 2018 Hiroshi Miura
#
image: Visual Studio 2017
max_jobs: 1

environment:
  matrix:
    - VCPKG_DEFAULT_TRIPLET: x86-windows
    - VCPKG_DEFAULT_TRIPLET: x86-windows-static
    - VCPKG_DEFAULT_TRIPLET: x64-windows
    - VCPKG_DEFAULT_TRIPLET: x64-windows-static

cache:
  - c:\tools\vcpkg\installed
  - c:\tools\vcpkg\packages

install:
  - cd C:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - .\vcpkg.exe remove --outdated
  - .\vcpkg.exe install curl

build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake %APPVEYOR_BUILD_FOLDER%
